attr {
    load = yes
    # Sources for below attribute.
    # https://www.scribd.com/document/696128249/Nokia-EPDG-Product-Description-Overview
    # https://www.cisco.com/c/en/us/td/docs/wireless/asr_5000/21-28/epdg-admin/21-28-epdg-admin.pdf
    # PCSCF IPv4 address.
    16389 = PCSCF_IP
    16384 = PCSCF_IP
    dns = SMF_DNS1, SMF_DNS2
}
